### ISSUE TITLE
Module state

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/base#11]
Right now Modules are initialised with [no running state](https://github.com/meteor-space/base/blob/develop/source/module.coffee#L19) since both `isRunning` and `isStopped` defaults to `false`, and there's no handling when the `start` and `stop` methods are called to update the opposing property. Seems like we would be better off merging these two into a single `state` property, defaulting it to 'stopped'.

Regarding `isReset`: It appears to be just tracking the fact that the Module has been reset at some point, which stops further resets in the running process since it's [being guarded](https://github.com/meteor-space/base/blob/develop/source/module.coffee#L95-L96), so we really need to straighten this out.

1. Is there any value in knowing that the module's state is currently `reset`? If not we can probably just remove this as the reset operation is idempotent.
2. Should the module be stopped before resetting? (abstracted so we can restart the module if it was running at the time reset was called)

**Comment by DominikGuzei** [comment]
Hey @rhyslbw!
Thanks for the deeper thoughts about this – you're right with all points and i would love to see this straightened out. i like the idea of having a single `state` property that is `stopped` by default and we can definitely remove the `isReset` property. Resetting should be idempotent as you said (didn't think too much obviously while implementing)

I would not say that the module has to be stopped before being reset, because resetting mostly means removing DB data (have not yet found any other use case).

**Comment by rhyslbw** [comment]
Ok great, so the only issue now is how to handle the reset.

Can you think of when we wouldn't want the  _stop_  operations run every time `reset` is called? (logic in the  _start_ that applies here should probably be in the  `afterInitialize`)

In my mind it makes sense that a _reset_ should only be done while the module is stopped, allowing logic in the _start_ to be run again as if starting up for the first time. As an implementor I expected the _start_ hooks to be triggered when I called `reset` on the running module (an app); it just seems to be more logical from a conceptual point of view. I can't think of a solid example but it seems like pulling the tablecloth out from under the app, and **might** introduce an inconsistent state, so it may be better to take the more cautious approach, then reconsider the idea of a _hot_ reset if the need arises.

**Comment by DominikGuzei** [comment]
Ah ok, yeah that sounds good to me – so `reset` is more like a restart that you can hook into.

**Comment by rhyslbw** [comment]
PR open https://github.com/meteor-space/base/pull/12
