### ISSUE TITLE
Breaking change: Space.Application.startup --> Space.Application.onStart

### ISSUE THREAD

**Issue by Sanjo** [meteor-space/base#16]
* This example is wrong: https://github.com/meteor-space/base#applications
* And missing in the upgrade guide: https://meteor-space.readme.io/v1.0/docs/upgrade-guide

Note: I use space:base@3.2.1.

**Comment by Sanjo** [comment]
The same applies to configure --> onInitialize

**Comment by DominikGuzei** [comment]
Hey @Sanjo, thanks for the feedback – we're in the middle of big changes and most of the readmes in the repos are outdated. They will soon be replaced with a simple intro + link to our new docs.

You can checkout the latest `Space.Application` API here:
https://meteor-space.readme.io/docs/application

**Comment by DominikGuzei** [comment]
The upgrade guide will follow soon, until then you can checkout the changelog to see the incremental updates etc.:
https://github.com/meteor-space/base/blob/develop/CHANGELOG.md

**Comment by DominikGuzei** [comment]
Migration guide is now available:
https://github.com/meteor-space/base#migration-guide
