### ISSUE TITLE
Feature/Versionable mixin

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/base#66]
# Background
- Currently versioning support for events is [hardcoded](https://github.com/meteor-space/messaging/blob/ea1be40eb837d3e75855ef8d1d62e84957e4da84/source/serializables/event.js#L6)
- It's also important for other serializables, but `eventVersion` is specific and needs to be either made generic or made configurable.
- This trait should be an option for any `Struct` given the feature is just to provide a transformation from one structure to another.

# Options

- configurable - Where would this be done?
- `schemaVersion`
- `structVersion`
- `version`

**Comment by rhyslbw** [comment]
I feel we should just pick a generic name and avoid the technical debt of a configurable option. My vote is simply for `version` unless there's a good reason not to

**Comment by DominikGuzei** [comment]
we cannot pick `version` since that collides with ES `version`. This really is more like a schema version. Another option could be `apiVersion`

**Comment by rhyslbw** [comment]
In that case I vote for `schemaVersion`

**Comment by darko-mijic** [comment]
`schemaVersion` makes more sense than `apiVersion` to me also.

**Comment by rhyslbw** [comment]
https://github.com/meteor-space/messaging/pull/29
